apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    pods: nginx-container
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: ssh
