apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    pods: phpmyadmin-container
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      targetPort: 5000
      name: http
