apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/dgascon/Documents/ft_services/srcs/mysql/databases
  persistentVolumeReclaimPolicy: Retain