apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          imagePullPolicy: Never
          image: services-ftps
