apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    pods: grafana-container
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      name: http